import { GoogleGenerativeAI } from "@google/generative-ai";
import { z } from "zod";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export const ParsedQuerySchema = z.object({
  productKeywords: z.string(),
  maxPrice: z.number().int().positive().nullable(),
  minPrice: z.number().int().positive().nullable(),
});

export type ParsedQuery = z.infer<typeof ParsedQuerySchema>;

export async function parseUserQueryWithAI(raw: string): Promise<ParsedQuery> {
  // allow overriding model via env var for flexibility
  const requestedModel = process.env.GEMINI_MODEL || "gemini-2.5-flash";

  const prompt = `Extract Flipkart search parameters from the user text below.
Return exactly and only a plain JSON string as output (as if generated by JSON.stringify): 
{
  "productKeywords": string,
  "maxPrice": number or null (in INR),
  "minPrice": number or null (in INR)
}

User text: "${raw}"
`;

  try {
    const model = genAI.getGenerativeModel({ model: requestedModel });
    const result = await model.generateContent(prompt);
    let text = result.response.text();

    text = text.trim();
    if (text.startsWith("```")) {
      // Remove the opening ```
      const firstLineBreak = text.indexOf("\n");
      text = text.slice(firstLineBreak + 1);
      // Remove the trailing ```
      const lastFence = text.lastIndexOf("```");
      if (lastFence !== -1) {
        text = text.slice(0, lastFence);
      }
      text = text.trim();
    }

    const json = JSON.parse(text);
    return ParsedQuerySchema.parse(json);
  } catch (err: any) {
    // If model is not found or API version mismatch, try to list available models to help debugging
    console.error(
      "[AI] generateContent failed for model:",
      requestedModel,
      "\nError:",
      err?.message || err
    );
    try {
      // SDK versions may differ; call listModels only if available.
      const listFn = (genAI as any).listModels;
      if (typeof listFn === "function") {
        const models = await listFn.call(genAI);
        console.error(
          "[AI] Available models:",
          JSON.stringify(models, null, 2)
        );
      } else {
        console.error(
          "[AI] listModels() is not available on this SDK instance."
        );
      }
    } catch (listErr) {
      console.error("[AI] Failed to list models:", listErr);
    }

    throw new Error(
      `AI model error: failed to generate content using model "${requestedModel}". ` +
        `Check server logs for available models and update GEMINI_MODEL environment variable to a supported model name.`
    );
  }
}
